/**
 * Mock architecture for InfraVerse — a fictional fintech / e-commerce platform
 * ("Northwind Commerce"). ~24 nodes in a layered topology (PRD §10.7, D7):
 *
 *   frontend → api gateways → services → datastores / external APIs
 *
 * Positions are hand-authored (D1): X = flow direction (entry on the left,
 * datastores on the right), Y = vertical tier, Z = depth spread.
 * One node (`payment-service`) starts in a `warning` state as a baseline.
 */

import type {
  ArchitectureGraph,
  EventLog,
  EventLogType,
  ServiceEdge,
  ServiceNode,
} from "./types";

export const mockNodes: ServiceNode[] = [
  // ---- Frontend tier ----------------------------------------------------
  {
    id: "web-storefront",
    name: "Web Storefront",
    type: "frontend",
    status: "healthy",
    owner: "Frontend Team",
    region: "us-east-1",
    latencyMs: 42,
    uptimePercentage: 99.98,
    requestsPerSecond: 1450,
    errorRatePercentage: 0.03,
    costPerHour: 4.2,
    position: { x: -11, y: 5, z: -1 },
  },
  {
    id: "admin-dashboard",
    name: "Admin Dashboard",
    type: "frontend",
    status: "healthy",
    owner: "Frontend Team",
    region: "eu-west-1",
    latencyMs: 55,
    uptimePercentage: 99.95,
    requestsPerSecond: 120,
    errorRatePercentage: 0.05,
    costPerHour: 2.1,
    position: { x: -11, y: 2.5, z: 2.5 },
  },

  // ---- API gateway tier -------------------------------------------------
  {
    id: "api-gateway",
    name: "API Gateway",
    type: "api",
    status: "healthy",
    owner: "Platform Team",
    region: "ap-south-1",
    latencyMs: 28,
    uptimePercentage: 99.99,
    requestsPerSecond: 1320,
    errorRatePercentage: 0.02,
    costPerHour: 6.5,
    position: { x: -7, y: 4.5, z: -0.5 },
  },
  {
    id: "mobile-gateway",
    name: "Mobile Gateway",
    type: "api",
    status: "healthy",
    owner: "Mobile Team",
    region: "ap-south-1",
    latencyMs: 33,
    uptimePercentage: 99.97,
    requestsPerSecond: 880,
    errorRatePercentage: 0.04,
    costPerHour: 5.1,
    position: { x: -7, y: 2, z: 2.5 },
  },

  // ---- Service tier -----------------------------------------------------
  {
    id: "auth-service",
    name: "Auth Service",
    type: "service",
    status: "healthy",
    owner: "Identity Team",
    region: "ap-south-1",
    latencyMs: 38,
    uptimePercentage: 99.98,
    requestsPerSecond: 1600,
    errorRatePercentage: 0.06,
    costPerHour: 5.8,
    position: { x: -3, y: 7, z: 0 },
  },
  {
    id: "user-service",
    name: "User Service",
    type: "service",
    status: "healthy",
    owner: "Identity Team",
    region: "ap-south-1",
    latencyMs: 46,
    uptimePercentage: 99.96,
    requestsPerSecond: 540,
    errorRatePercentage: 0.08,
    costPerHour: 3.9,
    position: { x: -3, y: 4.5, z: -3 },
  },
  {
    id: "product-service",
    name: "Product Catalog Service",
    type: "service",
    status: "healthy",
    owner: "Commerce Team",
    region: "ap-south-1",
    latencyMs: 52,
    uptimePercentage: 99.95,
    requestsPerSecond: 970,
    errorRatePercentage: 0.05,
    costPerHour: 4.6,
    position: { x: -3, y: 2, z: 3 },
  },
  {
    id: "cart-service",
    name: "Cart Service",
    type: "service",
    status: "healthy",
    owner: "Commerce Team",
    region: "ap-south-1",
    latencyMs: 61,
    uptimePercentage: 99.93,
    requestsPerSecond: 610,
    errorRatePercentage: 0.12,
    costPerHour: 4.3,
    position: { x: 0.5, y: 4.5, z: -1 },
  },
  {
    id: "order-service",
    name: "Order Service",
    type: "service",
    status: "healthy",
    owner: "Commerce Team",
    region: "ap-south-1",
    latencyMs: 88,
    uptimePercentage: 99.9,
    requestsPerSecond: 420,
    errorRatePercentage: 0.2,
    costPerHour: 6.1,
    position: { x: 0.5, y: 7, z: 2.5 },
  },
  {
    id: "inventory-service",
    name: "Inventory Service",
    type: "service",
    status: "healthy",
    owner: "Commerce Team",
    region: "ap-south-1",
    latencyMs: 70,
    uptimePercentage: 99.91,
    requestsPerSecond: 360,
    errorRatePercentage: 0.15,
    costPerHour: 4.8,
    position: { x: 0.5, y: 2, z: -3.5 },
  },
  {
    // Baseline warning node (D7) — elevated latency + error rate.
    id: "payment-service",
    name: "Payment Service",
    type: "service",
    status: "warning",
    owner: "Payments Team",
    region: "ap-south-1",
    latencyMs: 210,
    uptimePercentage: 99.7,
    requestsPerSecond: 380,
    errorRatePercentage: 1.4,
    costPerHour: 8.8,
    position: { x: 3.5, y: 6.5, z: -1.5 },
  },
  {
    id: "notification-service",
    name: "Notification Service",
    type: "service",
    status: "healthy",
    owner: "Messaging Team",
    region: "ap-south-1",
    latencyMs: 64,
    uptimePercentage: 99.92,
    requestsPerSecond: 290,
    errorRatePercentage: 0.18,
    costPerHour: 3.4,
    position: { x: 3.5, y: 4, z: 2.5 },
  },
  {
    id: "shipping-service",
    name: "Shipping Service",
    type: "service",
    status: "healthy",
    owner: "Fulfilment Team",
    region: "eu-west-1",
    latencyMs: 96,
    uptimePercentage: 99.89,
    requestsPerSecond: 210,
    errorRatePercentage: 0.25,
    costPerHour: 4.1,
    position: { x: 3.5, y: 1.5, z: 0 },
  },

  // ---- Datastore tier ---------------------------------------------------
  {
    id: "postgres-primary",
    name: "PostgreSQL Primary",
    type: "database",
    status: "healthy",
    owner: "Data Team",
    region: "ap-south-1",
    latencyMs: 16,
    uptimePercentage: 99.99,
    requestsPerSecond: 2100,
    errorRatePercentage: 0.01,
    costPerHour: 12.5,
    position: { x: 8, y: 6, z: -2 },
  },
  {
    id: "postgres-replica",
    name: "PostgreSQL Replica",
    type: "database",
    status: "healthy",
    owner: "Data Team",
    region: "us-east-1",
    latencyMs: 19,
    uptimePercentage: 99.98,
    requestsPerSecond: 980,
    errorRatePercentage: 0.01,
    costPerHour: 9.8,
    position: { x: 9.5, y: 6.5, z: -3.7 },
  },
  {
    id: "redis-cache",
    name: "Redis Cache",
    type: "cache",
    status: "healthy",
    owner: "Data Team",
    region: "ap-south-1",
    latencyMs: 4,
    uptimePercentage: 99.99,
    requestsPerSecond: 3400,
    errorRatePercentage: 0.0,
    costPerHour: 5.5,
    position: { x: 8, y: 3.5, z: 2.5 },
  },
  {
    id: "session-store",
    name: "Session Store",
    type: "cache",
    status: "healthy",
    owner: "Identity Team",
    region: "ap-south-1",
    latencyMs: 3,
    uptimePercentage: 99.99,
    requestsPerSecond: 1900,
    errorRatePercentage: 0.0,
    costPerHour: 3.8,
    position: { x: 9.5, y: 4, z: 4 },
  },
  {
    id: "order-queue",
    name: "Order Queue",
    type: "queue",
    status: "healthy",
    owner: "Messaging Team",
    region: "ap-south-1",
    latencyMs: 12,
    uptimePercentage: 99.97,
    requestsPerSecond: 460,
    errorRatePercentage: 0.03,
    costPerHour: 4.4,
    position: { x: 8, y: 1.5, z: -0.5 },
  },
  {
    id: "event-bus",
    name: "Event Bus",
    type: "queue",
    status: "healthy",
    owner: "Messaging Team",
    region: "ap-south-1",
    latencyMs: 9,
    uptimePercentage: 99.98,
    requestsPerSecond: 1250,
    errorRatePercentage: 0.02,
    costPerHour: 6.0,
    position: { x: 9.5, y: 1.8, z: 1.5 },
  },
  {
    id: "object-storage",
    name: "Object Storage",
    type: "storage",
    status: "healthy",
    owner: "Data Team",
    region: "us-east-1",
    latencyMs: 35,
    uptimePercentage: 99.99,
    requestsPerSecond: 540,
    errorRatePercentage: 0.02,
    costPerHour: 7.2,
    position: { x: 8.8, y: 7.5, z: 2.8 },
  },
  {
    id: "search-index",
    name: "Search Index",
    type: "database",
    status: "healthy",
    owner: "Data Team",
    region: "ap-south-1",
    latencyMs: 41,
    uptimePercentage: 99.94,
    requestsPerSecond: 720,
    errorRatePercentage: 0.09,
    costPerHour: 6.8,
    position: { x: 8.8, y: 1, z: -3 },
  },

  // ---- External APIs ----------------------------------------------------
  {
    id: "stripe-api",
    name: "Stripe Payments API",
    type: "external",
    status: "healthy",
    owner: "Payments Team",
    region: "us-east-1",
    latencyMs: 180,
    uptimePercentage: 99.95,
    requestsPerSecond: 360,
    errorRatePercentage: 0.3,
    costPerHour: 1.2,
    position: { x: 13, y: 5, z: 2.5 },
  },
  {
    id: "sendgrid-api",
    name: "SendGrid Email API",
    type: "external",
    status: "healthy",
    owner: "Messaging Team",
    region: "us-east-1",
    latencyMs: 240,
    uptimePercentage: 99.9,
    requestsPerSecond: 240,
    errorRatePercentage: 0.5,
    costPerHour: 0.6,
    position: { x: 13, y: 6.5, z: -1 },
  },
  {
    id: "shipping-carrier-api",
    name: "Shipping Carrier API",
    type: "external",
    status: "healthy",
    owner: "Fulfilment Team",
    region: "eu-west-1",
    latencyMs: 320,
    uptimePercentage: 99.8,
    requestsPerSecond: 180,
    errorRatePercentage: 0.8,
    costPerHour: 0.9,
    position: { x: 13, y: 2.5, z: -3 },
  },
];

/** Builds an edge with a derived id. `source` depends on / calls `target`. */
function edge(
  source: string,
  target: string,
  trafficRps: number,
  latencyMs: number,
  errorRatePercentage: number,
): ServiceEdge {
  return {
    id: `${source}__${target}`,
    source,
    target,
    trafficRps,
    latencyMs,
    errorRatePercentage,
  };
}

/**
 * Directed dependency edges — `source` calls `target`. 37 edges across the
 * layered topology. Failure propagates backward along these (D2a).
 */
export const mockEdges: ServiceEdge[] = [
  // ---- Frontend → gateway ----
  edge("web-storefront", "api-gateway", 1180, 30, 0.03),
  edge("web-storefront", "mobile-gateway", 740, 35, 0.04),
  edge("admin-dashboard", "api-gateway", 110, 40, 0.05),

  // ---- Gateway → service ----
  edge("api-gateway", "auth-service", 980, 38, 0.05),
  edge("api-gateway", "user-service", 360, 46, 0.07),
  edge("api-gateway", "product-service", 720, 52, 0.05),
  edge("api-gateway", "cart-service", 430, 60, 0.1),
  edge("api-gateway", "order-service", 280, 86, 0.18),
  edge("mobile-gateway", "auth-service", 540, 39, 0.06),
  edge("mobile-gateway", "product-service", 290, 54, 0.05),
  edge("mobile-gateway", "cart-service", 210, 62, 0.11),
  edge("mobile-gateway", "order-service", 160, 90, 0.2),

  // ---- Service → service ----
  edge("cart-service", "product-service", 380, 50, 0.05),
  edge("cart-service", "inventory-service", 250, 68, 0.13),
  edge("order-service", "payment-service", 240, 205, 1.3),
  edge("order-service", "inventory-service", 230, 70, 0.14),
  edge("order-service", "notification-service", 200, 64, 0.16),
  edge("order-service", "shipping-service", 150, 95, 0.22),
  edge("user-service", "auth-service", 320, 36, 0.05),
  edge("payment-service", "notification-service", 170, 62, 0.15),

  // ---- Service → datastore ----
  edge("auth-service", "session-store", 1500, 4, 0.0),
  edge("auth-service", "postgres-primary", 620, 17, 0.01),
  edge("user-service", "postgres-primary", 470, 18, 0.01),
  edge("product-service", "postgres-replica", 540, 20, 0.01),
  edge("product-service", "redis-cache", 1800, 4, 0.0),
  edge("product-service", "search-index", 610, 42, 0.08),
  edge("product-service", "object-storage", 320, 35, 0.02),
  edge("cart-service", "redis-cache", 980, 4, 0.0),
  edge("order-service", "postgres-primary", 410, 17, 0.01),
  edge("order-service", "order-queue", 360, 12, 0.03),
  edge("inventory-service", "postgres-primary", 340, 18, 0.02),
  edge("payment-service", "postgres-primary", 300, 19, 0.02),
  edge("notification-service", "event-bus", 280, 9, 0.02),
  edge("shipping-service", "postgres-replica", 190, 21, 0.02),

  // ---- Service → external ----
  edge("payment-service", "stripe-api", 220, 180, 0.3),
  edge("notification-service", "sendgrid-api", 210, 240, 0.5),
  edge("shipping-service", "shipping-carrier-api", 150, 320, 0.8),
];

/** The full mock architecture graph — the app's default dataset. */
export const mockGraph: ArchitectureGraph = {
  nodes: mockNodes,
  edges: mockEdges,
};

/** Builds an event-log entry with a derived id. */
function log(
  timestamp: string,
  serviceId: string,
  type: EventLogType,
  message: string,
): EventLog {
  return { id: `evt__${serviceId}__${timestamp}`, timestamp, serviceId, type, message };
}

/**
 * Seed event-timeline entries (oldest → newest). The two `payment-service`
 * warnings explain its baseline `warning` status; the simulation engine (M10)
 * appends further entries at runtime.
 */
export const mockEventLogs: EventLog[] = [
  log("2026-05-22T08:42:00Z", "api-gateway", "success", "Deployment completed — v2.18.3 rolled out"),
  log("2026-05-22T09:05:00Z", "redis-cache", "info", "Cache hit ratio steady at 96%"),
  log("2026-05-22T09:18:00Z", "postgres-primary", "warning", "Brief connection-pool saturation detected"),
  log("2026-05-22T09:19:00Z", "postgres-primary", "success", "Connection pool recovered to normal"),
  log("2026-05-22T09:33:00Z", "order-queue", "info", "Queue depth nominal (142 messages)"),
  log("2026-05-22T09:47:00Z", "payment-service", "warning", "Latency spike detected — p95 crossed 200ms"),
  log("2026-05-22T09:48:00Z", "payment-service", "warning", "Service degraded — error rate elevated to 1.4%"),
  log("2026-05-22T09:52:00Z", "stripe-api", "warning", "Upstream Stripe API latency elevated"),
  log("2026-05-22T10:04:00Z", "shipping-service", "info", "Carrier API retries within tolerance"),
  log("2026-05-22T10:15:00Z", "auth-service", "success", "Token cache warmed after deploy"),
  log("2026-05-22T10:22:00Z", "search-index", "info", "Reindex job completed in 4m 12s"),
  log("2026-05-22T10:31:00Z", "notification-service", "success", "Email backlog cleared"),
  log("2026-05-22T10:38:00Z", "event-bus", "info", "Throughput steady at ~1.2k msg/s"),
  log("2026-05-22T10:44:00Z", "web-storefront", "success", "CDN cache purged and revalidated"),
];
